---
- include: create-teamcity-user.yml
- include: mysql-connector.yml
  when: "teamcity_server_db_type == 'mysql'"
- include: postgresql-connector.yml
  when: "teamcity_server_db_type == 'postgresql'"
- include: teamcity-server.yml
- include: install-plugins.yml
- include: license.yml
